### ISSUE TITLE
Action does not work and docs are wrong.

### ISSUE THREAD

**Issue by chris-hinds** [dwardu89/aws-ssm-parameter-store#21]
It looks like the latest version of this action is broken.

First, the docs are wrong and link out to the incorrect action, which doesn't actually exist.

Secondly, when I actually load the action from this repo I see the following error

This is how I am using the action.

```
- name: Update deployed version in AWS SSM
        uses: dwardu89/aws-ssm-parameter-store@v2.0.1
        with:
          ssm-path: "deployed-version"
          ssm-value: "1.0.0"
          aws-region: us-east-1
          ssm-value-type: "String"
```

```
node:internal/modules/cjs/loader:936
Error: Cannot find module '@actions/core'
- /home/runner/work/_actions/dwardu89/aws-ssm-parameter-store/v2.0.1/index.js
```

**Comment by dwardu89** [comment]
Thank you, @chris-hinds  `v2.0.2` was released it was due to a bad merge
